name: ci

on:
  workflow_dispatch:
    inputs:
      loglevel:
        description: 'Log Level'
        required: true
        default:  'Warning'
        type:  choice
        options:
          - info
          - warning
          - debug
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 058264544314.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ vars.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
